export const styles = {
  root: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    p: 3,
    bgcolor: 'background.default',
  },
  paper: {
    maxWidth: 480,
    width: '100%',
    p: 5,
    borderRadius: 3,
    textAlign: 'center',
    border: '1px solid',
    borderColor: 'divider',
  },
  iconBox: {
    width: 72,
    height: 72,
    borderRadius: '50%',
    bgcolor: 'success.light',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    mx: 'auto',
    mb: 2.5,
  },
  icon: { fontSize: 40, color: 'success.main' },
}
