export const styles = {
  paper: {
    borderRadius: 3,
    overflow: 'hidden',
    border: '1px solid',
    borderColor: 'divider',
    mb: 2,
  },
  coverBox: {
    position: 'relative',
    height: { xs: 180, sm: 260 },
    bgcolor: 'action.hover',
    overflow: 'hidden',
  },
  coverImg: { width: '100%', height: '100%', objectFit: 'cover' },
  coverGradient: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #667eea22 0%, #764ba222 100%)',
  },
  coverUploadBtn: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    bgcolor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    '&:hover': { bgcolor: 'background.paper' },
  },
  avatar: {
    width: { xs: 100, sm: 130 },
    height: { xs: 100, sm: 130 },
    fontSize: 40,
    fontWeight: 700,
    border: '4px solid',
    borderColor: 'background.paper',
    bgcolor: 'primary.light',
    color: 'primary.main',
  },
  avatarUploadBtn: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    bgcolor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    width: 32,
    height: 32,
    '&:hover': { bgcolor: 'background.paper' },
  },
  nameBox: { flex: 1, pb: 0.5, textAlign: { xs: 'center', sm: 'left' } },
  chip: { fontSize: '0.7rem', height: 22, fontWeight: 600 },
}
